# Generated by Django 5.0.4 on 2024-04-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_expense_management_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_management',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
