# Generated by Django 5.0.4 on 2024-05-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_department_remove_category_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_management',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
