# Generated by Django 5.0.4 on 2024-05-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_date_created_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_management',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
